version: 2

jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Install libclang
          command: |
            gcc --version
            g++ --version
            apt-get -y update
            apt-get -y install libclang-dev libgcc-6-dev
      - run:
          name: Update rustc
          command: |
            rustup component add rustfmt-preview
            rustup update
      - run:
           name: Check formatting
           command: |
             rustfmt --version
             cargo fmt
             git diff --exit-code
      - run:
          name: Build
          command: RUST_LOG=debug cargo build --release -vv
      - run:
          name: Test
          command: cargo test -vv
